### ISSUE TITLE
add path option

### ISSUE THREAD

**Issue by andreasstieger** [Genivia/ugrep-indexer#1]
Hi, noticed that in [`deleter()`](https://github.com/Genivia/ugrep-indexer/blob/v0.9/src/ugrep-indexer.cpp#L936) and [`indexr()`](https://github.com/Genivia/ugrep-indexer/blob/v0.9/src/ugrep-indexer.cpp#L936) you start with the current (empty) path. Might be worth adding a path argument to avoid having to `chdir`

**Comment by genivia-inc** [comment]
Adding a path argument is a good idea. Perhaps ugrep-indexer should also take a path as an argument when provided? That way, the user doesn't need to chdir, as you point out.

Thanks for the suggestion!
