### ISSUE TITLE
Missing include <stdexcept> in zstream.hpp

### ISSUE THREAD

**Issue by geebakke** [Genivia/ugrep-indexer#11]
I cloned the repo and got the following error when running the build.sh script

```
In file included from ugrep-indexer.cpp:213:0:
zstream.hpp: In constructor 'zstreambuf::ZipInfo::sz_stream::sz_stream(const char*, FILE*)':
zstream.hpp:140:17: error: 'invalid_argument' is not a member of 'std'
           throw std::invalid_argument(pathname);
```

I included the \<stdexcept\> header in zstream.hpp and that seemed to fix the build issue.

**Comment by genivia-inc** [comment]
Yep, that should be there. Thanks for letting me know.

**Comment by genivia-inc** [comment]
Will update the indexer soon. Ugrep 5 will be released soon, which will also include an updated index search. This improvement does away with the "leading wildcard" pattern limitation, e.g. matching `[a-z]+something` is no problem (currently `[a-z]+` creates an index hash finite state automaton that matches too much).
